# Generated by Django 6.0.3 on 2026-05-16 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=128)),
                ('window', models.CharField(max_length=10)),
                ('count', models.PositiveIntegerField(default=0)),
                ('reset_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Rate Limit Bucket',
                'verbose_name_plural': 'Rate Limit Buckets',
                'unique_together': {('identifier', 'window')},
            },
        ),
        migrations.CreateModel(
            name='AIInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('vendor', 'Vendor'), ('customer', 'Customer'), ('guest', 'Guest')], default='guest', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('feature', models.CharField(choices=[('chat', 'General Chat'), ('food_gen', 'Food Item Generator'), ('price_cmp', 'Price Comparison'), ('recommend', 'Food Recommendations'), ('order_track', 'Order Tracking'), ('reorder', 'Reorder Suggestions'), ('nearby', 'Nearby Restaurants'), ('vendor_info', 'Vendor Info')], default='chat', max_length=30)),
                ('user_message', models.TextField(blank=True)),
                ('ai_reply', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=120)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Interaction Log',
                'verbose_name_plural': 'AI Interaction Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role', 'created_at'], name='ai_assistan_role_776535_idx'), models.Index(fields=['feature', 'created_at'], name='ai_assistan_feature_7392b9_idx'), models.Index(fields=['success', 'created_at'], name='ai_assistan_success_a8441e_idx'), models.Index(fields=['user', 'created_at'], name='ai_assistan_user_id_407427_idx')],
            },
        ),
    ]
