# Generated by Django 6.0.3 on 2026-05-17 07:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_ratelimitbucket_aiinteractionlog'),
        ('menu', '0004_alter_fooditem_image'),
        ('orders', '0003_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinteractionlog',
            name='feature',
            field=models.CharField(choices=[('chat', 'General Chat'), ('food_gen', 'Food Item Generator'), ('price_cmp', 'Price Comparison'), ('recommend', 'Food Recommendations'), ('order_track', 'Order Tracking'), ('reorder', 'Reorder Suggestions'), ('nearby', 'Nearby Restaurants'), ('vendor_info', 'Vendor Info'), ('review_submit', 'Review Submission'), ('review_nudge', 'Review Nudge'), ('recommend_rated', 'Rated Recommendations'), ('onboarding', 'Onboarding Tour')], default='chat', max_length=30),
        ),
        migrations.CreateModel(
            name='FoodReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5.0)])),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='review_images/')),
                ('is_verified_purchase', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_reviews', to=settings.AUTH_USER_MODEL)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='menu.fooditem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderedfood')),
            ],
            options={
                'verbose_name': 'Food Review',
                'verbose_name_plural': 'Food Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'order_item')},
            },
        ),
        migrations.CreateModel(
            name='OnboardingTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_completed', models.BooleanField(default=False)),
                ('tour_step', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.CharField(max_length=128)),
                ('window', models.CharField(max_length=10)),
                ('count', models.PositiveIntegerField(default=0)),
                ('reset_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rate Limit Bucket',
                'verbose_name_plural': 'Rate Limit Buckets',
                'unique_together': {('identifier', 'window')},
            },
        ),
        migrations.CreateModel(
            name='ReviewReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dismissed', models.BooleanField(default=False)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reminders', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderedfood')),
            ],
            options={
                'verbose_name': 'Review Reminder',
                'verbose_name_plural': 'Review Reminders',
                'unique_together': {('customer', 'order_item')},
            },
        ),
    ]
