# Generated by Django 6.0.3 on 2026-05-17 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_alter_aiinteractionlog_feature_foodreview_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingtour',
            options={'verbose_name': 'Onboarding Tour', 'verbose_name_plural': 'Onboarding Tours'},
        ),
        migrations.AlterUniqueTogether(
            name='onboardingtour',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='onboardingtour',
            name='count',
        ),
        migrations.RemoveField(
            model_name='onboardingtour',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='onboardingtour',
            name='reset_at',
        ),
        migrations.RemoveField(
            model_name='onboardingtour',
            name='window',
        ),
    ]
