# Generated by Django 6.0.3 on 2026-05-17 10:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0004_alter_onboardingtour_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreview',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
