# Generated by Django 6.0.3 on 2026-07-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_alter_foodreview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images'),
        ),
    ]
